name: Cleanup Workflow History

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # 获取工作流列表并针对每个工作流保留最新的 2 个记录
          WORKFLOW_NAME="server_renew.yml"
          
          echo "Cleaning up runs for $WORKFLOW_NAME..."
          
          # 获取所有运行记录的 ID，排除掉最新的 2 条，然后删除剩下的
          gh run list --workflow "$WORKFLOW_NAME" --limit 100 --json databaseId  --jq '.[2:].[] | .databaseId' | \
          xargs -I{} gh run delete {}
